---
# tasks file for ssh

- name: Create "/home/{{ user }}/.ssh" directory
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    mode: 0700

- name: Copy "authorized_keys" to "/home/{{ user }}/.ssh/" directory
  copy:
    src: authorized_keys
    dest: /home/{{ user }}/.ssh/authorized_keys
    mode: 0600
